[2022-12-26T13:58:35.798+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: exchange_rates.insert_rate_USD_RUB scheduled__2022-06-25T08:15:00+00:00 [queued]>
[2022-12-26T13:58:35.823+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: exchange_rates.insert_rate_USD_RUB scheduled__2022-06-25T08:15:00+00:00 [queued]>
[2022-12-26T13:58:35.823+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-12-26T13:58:35.824+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-12-26T13:58:35.826+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-12-26T13:58:35.844+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): insert_rate_USD_RUB> on 2022-06-25 08:15:00+00:00
[2022-12-26T13:58:35.848+0000] {standard_task_runner.py:54} INFO - Started process 8365 to run task
[2022-12-26T13:58:35.874+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'exchange_rates', 'insert_rate_USD_RUB', 'scheduled__2022-06-25T08:15:00+00:00', '--job-id', '4254', '--raw', '--subdir', 'DAGS_FOLDER/exchange_rates.py', '--cfg-path', '/tmp/tmp1ayzxzoi']
[2022-12-26T13:58:35.895+0000] {standard_task_runner.py:83} INFO - Job 4254: Subtask insert_rate_USD_RUB
[2022-12-26T13:58:35.898+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/exchange_rates.py
[2022-12-26T13:58:36.247+0000] {taskmixin.py:205} WARNING - Dependency <Task(CurrencyScoopOperator): get_rate_AMD_RUB>, insert_rate_AMD_RUB already registered for DAG: exchange_rates
[2022-12-26T13:58:36.255+0000] {taskmixin.py:205} WARNING - Dependency <Task(PostgresOperator): insert_rate_AMD_RUB>, get_rate_AMD_RUB already registered for DAG: exchange_rates
[2022-12-26T13:58:36.494+0000] {task_command.py:384} INFO - Running <TaskInstance: exchange_rates.insert_rate_USD_RUB scheduled__2022-06-25T08:15:00+00:00 [running]> on host d383fbf2a8e7
[2022-12-26T13:58:36.599+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:204: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-12-26T13:58:36.761+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=exchange_rates
AIRFLOW_CTX_TASK_ID=insert_rate_USD_RUB
AIRFLOW_CTX_EXECUTION_DATE=2022-06-25T08:15:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-25T08:15:00+00:00
[2022-12-26T13:58:36.787+0000] {base.py:71} INFO - Using connection ID 'postgres_default' for task execution.
[2022-12-26T13:58:36.789+0000] {sql.py:315} INFO - Running statement: INSERT INTO
    exchange_rates
VALUES ('USD', 'RUB', None, '2022-06-25')
ON CONFLICT (base, currency, date) DO
    UPDATE
        SET rate = excluded.rate;, parameters: None
[2022-12-26T13:58:36.792+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 94, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 295, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 320, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedColumn: column "none" does not exist
LINE 3: VALUES ('USD', 'RUB', None, '2022-06-25')
                              ^

[2022-12-26T13:58:36.805+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=exchange_rates, task_id=insert_rate_USD_RUB, execution_date=20220625T081500, start_date=20221226T135835, end_date=20221226T135836
[2022-12-26T13:58:36.864+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 4254 for task insert_rate_USD_RUB (column "none" does not exist
LINE 3: VALUES ('USD', 'RUB', None, '2022-06-25')
                              ^
; 8365)
[2022-12-26T13:58:36.917+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-12-26T13:58:36.971+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-01-01T14:42:42.731+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: exchange_rates.insert_rate_USD_RUB scheduled__2022-06-25T08:15:00+00:00 [queued]>
[2023-01-01T14:42:42.778+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: exchange_rates.insert_rate_USD_RUB scheduled__2022-06-25T08:15:00+00:00 [queued]>
[2023-01-01T14:42:42.781+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-01-01T14:42:42.783+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-01-01T14:42:42.784+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-01-01T14:42:42.853+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): insert_rate_USD_RUB> on 2022-06-25 08:15:00+00:00
[2023-01-01T14:42:42.859+0000] {standard_task_runner.py:54} INFO - Started process 8994 to run task
[2023-01-01T14:42:42.880+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'exchange_rates', 'insert_rate_USD_RUB', 'scheduled__2022-06-25T08:15:00+00:00', '--job-id', '10236', '--raw', '--subdir', 'DAGS_FOLDER/exchange_rates.py', '--cfg-path', '/tmp/tmp5gh1suif']
[2023-01-01T14:42:42.881+0000] {standard_task_runner.py:83} INFO - Job 10236: Subtask insert_rate_USD_RUB
[2023-01-01T14:42:42.882+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/exchange_rates.py
[2023-01-01T14:42:43.173+0000] {taskmixin.py:205} WARNING - Dependency <Task(CurrencyScoopOperator): get_rate_AMD_RUB>, insert_rate_AMD_RUB already registered for DAG: exchange_rates
[2023-01-01T14:42:43.181+0000] {taskmixin.py:205} WARNING - Dependency <Task(PostgresOperator): insert_rate_AMD_RUB>, get_rate_AMD_RUB already registered for DAG: exchange_rates
[2023-01-01T14:42:43.397+0000] {task_command.py:384} INFO - Running <TaskInstance: exchange_rates.insert_rate_USD_RUB scheduled__2022-06-25T08:15:00+00:00 [running]> on host d383fbf2a8e7
[2023-01-01T14:42:43.555+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:204: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-01-01T14:42:43.739+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=exchange_rates
AIRFLOW_CTX_TASK_ID=insert_rate_USD_RUB
AIRFLOW_CTX_EXECUTION_DATE=2022-06-25T08:15:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-25T08:15:00+00:00
[2023-01-01T14:42:43.761+0000] {base.py:71} INFO - Using connection ID 'postgres_default' for task execution.
[2023-01-01T14:42:43.770+0000] {sql.py:315} INFO - Running statement: INSERT INTO
    exchange_rates
VALUES ('USD', 'RUB', None, '2022-06-25')
ON CONFLICT (base, currency, date) DO
    UPDATE
        SET rate = excluded.rate;, parameters: None
[2023-01-01T14:42:43.772+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 94, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 295, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 320, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedColumn: column "none" does not exist
LINE 3: VALUES ('USD', 'RUB', None, '2022-06-25')
                              ^

[2023-01-01T14:42:43.787+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=exchange_rates, task_id=insert_rate_USD_RUB, execution_date=20220625T081500, start_date=20230101T144242, end_date=20230101T144243
[2023-01-01T14:42:43.799+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 10236 for task insert_rate_USD_RUB (column "none" does not exist
LINE 3: VALUES ('USD', 'RUB', None, '2022-06-25')
                              ^
; 8994)
[2023-01-01T14:42:43.855+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-01-01T14:42:43.884+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
