[2022-12-26T13:58:36.370+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: exchange_rates.insert_rate_AMD_RUB scheduled__2022-06-25T08:15:00+00:00 [queued]>
[2022-12-26T13:58:36.424+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: exchange_rates.insert_rate_AMD_RUB scheduled__2022-06-25T08:15:00+00:00 [queued]>
[2022-12-26T13:58:36.425+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-12-26T13:58:36.426+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-12-26T13:58:36.427+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-12-26T13:58:36.483+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): insert_rate_AMD_RUB> on 2022-06-25 08:15:00+00:00
[2022-12-26T13:58:36.496+0000] {standard_task_runner.py:54} INFO - Started process 8374 to run task
[2022-12-26T13:58:36.500+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'exchange_rates', 'insert_rate_AMD_RUB', 'scheduled__2022-06-25T08:15:00+00:00', '--job-id', '4260', '--raw', '--subdir', 'DAGS_FOLDER/exchange_rates.py', '--cfg-path', '/tmp/tmpbbpjszs7']
[2022-12-26T13:58:36.509+0000] {standard_task_runner.py:83} INFO - Job 4260: Subtask insert_rate_AMD_RUB
[2022-12-26T13:58:36.510+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/exchange_rates.py
[2022-12-26T13:58:36.607+0000] {taskmixin.py:205} WARNING - Dependency <Task(CurrencyScoopOperator): get_rate_AMD_RUB>, insert_rate_AMD_RUB already registered for DAG: exchange_rates
[2022-12-26T13:58:36.612+0000] {taskmixin.py:205} WARNING - Dependency <Task(PostgresOperator): insert_rate_AMD_RUB>, get_rate_AMD_RUB already registered for DAG: exchange_rates
[2022-12-26T13:58:36.834+0000] {task_command.py:384} INFO - Running <TaskInstance: exchange_rates.insert_rate_AMD_RUB scheduled__2022-06-25T08:15:00+00:00 [running]> on host d383fbf2a8e7
[2022-12-26T13:58:36.918+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:204: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-12-26T13:58:37.097+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=exchange_rates
AIRFLOW_CTX_TASK_ID=insert_rate_AMD_RUB
AIRFLOW_CTX_EXECUTION_DATE=2022-06-25T08:15:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-25T08:15:00+00:00
[2022-12-26T13:58:37.124+0000] {base.py:71} INFO - Using connection ID 'postgres_default' for task execution.
[2022-12-26T13:58:37.131+0000] {sql.py:315} INFO - Running statement: INSERT INTO
    exchange_rates
VALUES ('AMD', 'RUB', None, '2022-06-25')
ON CONFLICT (base, currency, date) DO
    UPDATE
        SET rate = excluded.rate;, parameters: None
[2022-12-26T13:58:37.132+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 94, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 295, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 320, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedColumn: column "none" does not exist
LINE 3: VALUES ('AMD', 'RUB', None, '2022-06-25')
                              ^

[2022-12-26T13:58:37.143+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=exchange_rates, task_id=insert_rate_AMD_RUB, execution_date=20220625T081500, start_date=20221226T135836, end_date=20221226T135837
[2022-12-26T13:58:37.191+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 4260 for task insert_rate_AMD_RUB (column "none" does not exist
LINE 3: VALUES ('AMD', 'RUB', None, '2022-06-25')
                              ^
; 8374)
[2022-12-26T13:58:37.217+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-12-26T13:58:37.250+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-01-01T14:42:42.841+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: exchange_rates.insert_rate_AMD_RUB scheduled__2022-06-25T08:15:00+00:00 [queued]>
[2023-01-01T14:42:42.876+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: exchange_rates.insert_rate_AMD_RUB scheduled__2022-06-25T08:15:00+00:00 [queued]>
[2023-01-01T14:42:42.877+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-01-01T14:42:42.879+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-01-01T14:42:42.880+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-01-01T14:42:42.908+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): insert_rate_AMD_RUB> on 2022-06-25 08:15:00+00:00
[2023-01-01T14:42:42.911+0000] {standard_task_runner.py:54} INFO - Started process 8996 to run task
[2023-01-01T14:42:42.954+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'exchange_rates', 'insert_rate_AMD_RUB', 'scheduled__2022-06-25T08:15:00+00:00', '--job-id', '10239', '--raw', '--subdir', 'DAGS_FOLDER/exchange_rates.py', '--cfg-path', '/tmp/tmpmqq9_22p']
[2023-01-01T14:42:42.957+0000] {standard_task_runner.py:83} INFO - Job 10239: Subtask insert_rate_AMD_RUB
[2023-01-01T14:42:42.959+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/exchange_rates.py
[2023-01-01T14:42:43.231+0000] {taskmixin.py:205} WARNING - Dependency <Task(CurrencyScoopOperator): get_rate_AMD_RUB>, insert_rate_AMD_RUB already registered for DAG: exchange_rates
[2023-01-01T14:42:43.238+0000] {taskmixin.py:205} WARNING - Dependency <Task(PostgresOperator): insert_rate_AMD_RUB>, get_rate_AMD_RUB already registered for DAG: exchange_rates
[2023-01-01T14:42:43.446+0000] {task_command.py:384} INFO - Running <TaskInstance: exchange_rates.insert_rate_AMD_RUB scheduled__2022-06-25T08:15:00+00:00 [running]> on host d383fbf2a8e7
[2023-01-01T14:42:43.521+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:204: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-01-01T14:42:43.638+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=exchange_rates
AIRFLOW_CTX_TASK_ID=insert_rate_AMD_RUB
AIRFLOW_CTX_EXECUTION_DATE=2022-06-25T08:15:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-25T08:15:00+00:00
[2023-01-01T14:42:43.674+0000] {base.py:71} INFO - Using connection ID 'postgres_default' for task execution.
[2023-01-01T14:42:43.697+0000] {sql.py:315} INFO - Running statement: INSERT INTO
    exchange_rates
VALUES ('AMD', 'RUB', None, '2022-06-25')
ON CONFLICT (base, currency, date) DO
    UPDATE
        SET rate = excluded.rate;, parameters: None
[2023-01-01T14:42:43.699+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 94, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 295, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 320, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedColumn: column "none" does not exist
LINE 3: VALUES ('AMD', 'RUB', None, '2022-06-25')
                              ^

[2023-01-01T14:42:43.711+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=exchange_rates, task_id=insert_rate_AMD_RUB, execution_date=20220625T081500, start_date=20230101T144242, end_date=20230101T144243
[2023-01-01T14:42:43.743+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 10239 for task insert_rate_AMD_RUB (column "none" does not exist
LINE 3: VALUES ('AMD', 'RUB', None, '2022-06-25')
                              ^
; 8996)
[2023-01-01T14:42:43.783+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-01-01T14:42:43.811+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
